/* ── STATE & i18n ── */

export const i18n = {
  'en': {
    'home': 'Home',
    'pnr_status': 'PNR Status',
    'live_tracking': 'Live Tracking',
    'login': 'Login / Register',
    'logout': 'Logout',
    'my_account': 'My Account',
    'hello': 'Hello',
    'book_ticket': 'BOOK TICKET',
    'from_station': 'From Station',
    'to_station': 'To Station',
    'journey_date': 'Journey Date',
    'find_trains': 'Find Trains',
    'pnr_status_check': 'Check PNR Status',
    'pnr_placeholder': 'e.g. 4235678901',
    'track_status': 'Track Status',
    'search_trains': 'Search Trains',
    'passenger_details': 'Passenger Details',
    'confirm_pay': 'Confirm & Pay',
    'total_amount': 'Total Amount',
    'no_trains_found': 'No trains found for this route and date.',
    'live_status': 'LIVE STATUS',
    'smartest_way': 'The Smartest Way <br/>to Travel by Rail.',
    'book_track_pnr': 'Book tickets, track trains in real-time, and get instant updates on PNR status with AeroRail.',
    'check_pnr_desc': 'Enter your 10-digit PNR number to get live status.',
    'book_now': 'Book Now',
    'modify_search': 'Modify Search',
    'pnr_status_label': 'PNR Status',
    'charts_vacancy': 'Charts / Vacancy',
    'train_name_number': 'Train Name / Number',
    'boarding_station': 'Boarding Station',
    'get_train_chart': 'Get Train Chart',
    'enter_city_station': 'Enter City/Station',
    'live_train_tracking': 'Live Train Tracking',
    'enter_train_number': 'Enter train number to see real-time location and status.',
    'track_now': 'Track Now',
    'my_bookings': 'My Bookings',
    'manage_journeys': 'Manage your upcoming and past journeys.',
    'no_bookings': 'No bookings found.',
    'ticket_pdf': 'Ticket PDF',
    'confirmed': 'CONFIRMED',
    'journey_date_label': 'JOURNEY DATE',
    'from_label': 'FROM',
    'to_label': 'TO',
    'download_ticket': 'Download E-Ticket (PDF)',
    'please_login_book': 'Please login to book a ticket',
    'registration_success': 'Registration successful! Please login.',
    'logged_in': 'Logged in successfully',
    'login_modal_title': 'Welcome Back',
    'login_modal_desc': 'Login to access bookings and profiles.',
    'register_modal_title': 'Join AeroRail',
    'register_modal_desc': 'Create your account to start booking.',
    'username': 'Username',
    'password': 'Password',
    'dont_have_account': 'Don\'t have an account?',
    'register_link': 'Register',
    'already_have_account': 'Already have an account?',
    'login_link': 'Login',
    'language': 'Language'
  },
  'hi': {
    'home': 'होम',
    'pnr_status': 'PNR स्थिति',
    'live_tracking': 'लाइव ट्रैकिंग',
    'login': 'लॉगिन / पंजीकरण',
    'logout': 'लॉगआउट',
    'my_account': 'मेरा खाता',
    'hello': 'नमस्ते',
    'book_ticket': 'टिकट बुक करें',
    'from_station': 'स्टेशन से',
    'to_station': 'स्टेशन तक',
    'journey_date': 'यात्रा की तारीख',
    'find_trains': 'ट्रेनें खोजें',
    'pnr_status_check': 'PNR स्थिति जांचें',
    'pnr_placeholder': 'उदा. 4235678901',
    'track_status': 'स्थिति ट्रैक करें',
    'search_trains': 'ट्रेनें खोजें',
    'passenger_details': 'यात्री विवरण',
    'confirm_pay': 'पुष्टि और भुगतान करें',
    'total_amount': 'कुल राशि',
    'no_trains_found': 'इस रूट और तारीख के लिए कोई ट्रेन नहीं मिली।',
    'live_status': 'लाइव स्थिति',
    'smartest_way': 'रेल से यात्रा करने का सबसे स्मार्ट तरीका।',
    'book_track_pnr': 'टिकट बुक करें, ट्रेनों को रीयल-टाइम में ट्रैक करें, और PNR स्थिति पर तत्काल अपडेट प्राप्त करें।',
    'check_pnr_desc': 'अपने 10-अंकीय PNR नंबर दर्ज करें लाइव स्थिति प्राप्त करने के लिए।',
    'book_now': 'अभी बुक करें',
    'modify_search': 'खोज संशोधित करें',
    'pnr_status_label': 'PNR स्थिति',
    'charts_vacancy': 'चार्ट / रिक्तता',
    'train_name_number': 'ट्रेन का नाम / संख्या',
    'boarding_station': 'बोर्डिंग स्टेशन',
    'get_train_chart': 'ट्रेन चार्ट प्राप्त करें',
    'enter_city_station': 'शहर/स्टेशन दर्ज करें',
    'live_train_tracking': 'लाइव ट्रेन ट्रैकिंग',
    'enter_train_number': 'रीयल-टाइम स्थान और स्थिति देखने के लिए ट्रेन संख्या दर्ज करें।',
    'track_now': 'अभी ट्रैक करें',
    'my_bookings': 'मेरी बुकिंगें',
    'manage_journeys': 'अपनी आने वाली और पिछली यात्राओं को प्रबंधित करें।',
    'no_bookings': 'कोई बुकिंग नहीं मिली।',
    'ticket_pdf': 'टिकट PDF',
    'confirmed': 'पुष्टि की गई',
    'journey_date_label': 'यात्रा की तारीख',
    'from_label': 'स्टेशन से',
    'to_label': 'स्टेशन तक',
    'download_ticket': 'E-Ticket डाउनलोड करें (PDF)',
    'please_login_book': 'टिकट बुक करने के लिए कृपया लॉगिन करें',
    'registration_success': 'पंजीकरण सफल! कृपया लॉगिन करें।',
    'logged_in': 'सफलतापूर्वक लॉगिन किया गया',
    'login_modal_title': 'स्वागत है',
    'login_modal_desc': 'बुकिंग और प्रोफाइल तक पहुंचने के लिए लॉगिन करें।',
    'register_modal_title': 'AeroRail में शामिल हों',
    'register_modal_desc': 'बुकिंग शुरू करने के लिए अपना खाता बनाएं।',
    'username': 'उपयोगकर्ता नाम',
    'password': 'पासवर्ड',
    'dont_have_account': 'खाता नहीं है?',
    'register_link': 'पंजीकरण करें',
    'already_have_account': 'पहले से खाता है?',
    'login_link': 'लॉगिन',
    'language': 'भाषा'
  }
};

export const state = {
    user: null,
    role: 'customer',
    currentPath: window.location.pathname,
    searchResults: [],
    selectedTrain: null,
    isRegistering: false,
    language: localStorage.getItem('aeroRailLanguage') || 'en'
};

export function t(key) {
    return i18n[state.language] && i18n[state.language][key]
        ? i18n[state.language][key]
        : i18n['en'][key] || key;
}
