/* STATE & i18n */

export const SUPPORTED_LANGUAGES = [
    { code: 'en', name: 'English' },
    { code: 'as', name: 'অসমীয়া' },
    { code: 'bn', name: 'বাংলা' },
    { code: 'brx', name: 'बड़ो' },
    { code: 'doi', name: 'डोगरी' },
    { code: 'gu', name: 'ગુજરાતી' },
    { code: 'hi', name: 'हिन्दी' },
    { code: 'kn', name: 'ಕನ್ನಡ' },
    { code: 'ks', name: 'کٲشُر' },
    { code: 'kok', name: 'कोंकणी' },
    { code: 'mai', name: 'मैथिली' },
    { code: 'ml', name: 'മലയാളം' },
    { code: 'mni', name: 'মৈতৈলোন্' },
    { code: 'mr', name: 'मराठी' },
    { code: 'ne', name: 'नेपाली' },
    { code: 'or', name: 'ଓଡ଼ିଆ' },
    { code: 'pa', name: 'ਪੰਜਾਬੀ' },
    { code: 'sa', name: 'संस्कृतम्' },
    { code: 'sat', name: 'ᱥᱟᱱᱛᱟᱲᱤ' },
    { code: 'sd', name: 'سنڌي' },
    { code: 'ta', name: 'தமிழ்' },
    { code: 'te', name: 'తెలుగు' },
    { code: 'ur', name: 'اردو' },
];

const en = {
    home: 'Home',
    pnr_status: 'PNR Status',
    live_tracking: 'Live Tracking',
    login: 'Login / Register',
    logout: 'Logout',
    my_account: 'My Account',
    hello: 'Hello',
    book_ticket: 'BOOK TICKET',
    from_station: 'From Station',
    to_station: 'To Station',
    journey_date: 'Journey Date',
    find_trains: 'Find Trains',
    pnr_status_check: 'Check PNR Status',
    pnr_placeholder: 'e.g. 4235678901',
    track_status: 'Track Status',
    search_trains: 'Search Trains',
    passenger_details: 'Passenger Details',
    confirm_pay: 'Confirm & Pay',
    total_amount: 'Total Amount',
    no_trains_found: 'No trains found for this route and date.',
    live_status: 'LIVE STATUS',
    smartest_way: 'The Smartest Way <br/>to Travel by Rail.',
    book_track_pnr: 'Book tickets, track trains in real-time, and get instant updates on PNR status with AeroRail.',
    check_pnr_desc: 'Enter your 10-digit PNR number to get live status.',
    book_now: 'Book Now',
    modify_search: 'Modify Search',
    pnr_status_label: 'PNR Status',
    charts_vacancy: 'Charts / Vacancy',
    train_name_number: 'Train Name / Number',
    boarding_station: 'Boarding Station',
    get_train_chart: 'Get Train Chart',
    enter_city_station: 'Enter City/Station',
    live_train_tracking: 'Live Train Tracking',
    enter_train_number: 'Enter train number to see real-time location and status.',
    track_now: 'Track Now',
    my_bookings: 'My Bookings',
    manage_journeys: 'Manage your upcoming and past journeys.',
    no_bookings: 'No bookings found.',
    ticket_pdf: 'Ticket PDF',
    confirmed: 'CONFIRMED',
    journey_date_label: 'JOURNEY DATE',
    from_label: 'FROM',
    to_label: 'TO',
    download_ticket: 'Download E-Ticket (PDF)',
    please_login_book: 'Please login to book a ticket',
    registration_success: 'Registration successful! Please login.',
    logged_in: 'Logged in successfully',
    login_modal_title: 'Welcome Back',
    login_modal_desc: 'Login to access bookings and profiles.',
    register_modal_title: 'Join AeroRail',
    register_modal_desc: 'Create your account to start booking.',
    username: 'Username',
    password: 'Password',
    dont_have_account: "Don't have an account?",
    register_link: 'Register',
    already_have_account: 'Already have an account?',
    login_link: 'Login',
    language: 'Language',
    create_account: 'Create Account', 
    my_profile: 'My Profile',
    profile_details: 'Your Profile Details',
    continue: 'Continue'
};

const languageOverrides = {
    as: {
        home: 'ঘৰ', pnr_status: 'PNR স্থিতি', live_tracking: 'লাইভ ট্ৰেকিং', login: 'লগইন / পঞ্জীয়ন', logout: 'লগআউট', my_account: 'মোৰ একাউণ্ট', hello: 'নমস্কাৰ',
        book_ticket: 'টিকট বুক কৰক', from_station: 'প্ৰস্থান ষ্টেচন', to_station: 'গন্তব্য ষ্টেচন', journey_date: 'যাত্ৰাৰ তাৰিখ', find_trains: 'ট্ৰেইন বিচাৰক',
        pnr_status_check: 'PNR স্থিতি চাওক', track_status: 'স্থিতি চাওক', search_trains: 'ট্ৰেইন বিচাৰক', passenger_details: 'যাত্ৰীৰ বিৱৰণ', confirm_pay: 'নিশ্চিত কৰি পে কৰক',
        total_amount: 'মুঠ পৰিমাণ', no_trains_found: 'এই পথ আৰু তাৰিখৰ বাবে ট্ৰেইন পোৱা নগল।', live_status: 'লাইভ স্থিতি',
        smartest_way: 'ৰেলেৰে যাত্ৰাৰ <br/>স্মাৰ্ট উপায়।', book_track_pnr: 'টিকট বুক কৰক, ট্ৰেইন লাইভ ট্ৰেক কৰক, আৰু PNR আপডেট পাওক।',
        check_pnr_desc: 'লাইভ স্থিতিৰ বাবে আপোনাৰ ১০-অংকৰ PNR নম্বৰ লিখক।', book_now: 'এতিয়াই বুক কৰক', pnr_status_label: 'PNR স্থিতি',
        charts_vacancy: 'চাৰ্ট / খালী আসন', train_name_number: 'ট্ৰেইনৰ নাম / নম্বৰ', boarding_station: 'ব’ৰ্ডিং ষ্টেচন', get_train_chart: 'ট্ৰেইন চাৰ্ট পাওক',
        enter_city_station: 'চহৰ/ষ্টেচন লিখক', live_train_tracking: 'লাইভ ট্ৰেইন ট্ৰেকিং', enter_train_number: 'লাইভ অৱস্থান আৰু স্থিতিৰ বাবে ট্ৰেইন নম্বৰ লিখক।',
        track_now: 'এতিয়াই ট্ৰেক কৰক', my_bookings: 'মোৰ বুকিংসমূহ', manage_journeys: 'আপোনাৰ যাত্ৰাসমূহ পৰিচালনা কৰক।', no_bookings: 'কোনো বুকিং পোৱা নগল।',
        ticket_pdf: 'টিকট PDF', confirmed: 'নিশ্চিত', journey_date_label: 'যাত্ৰাৰ তাৰিখ', from_label: 'পৰা', to_label: 'লৈ', download_ticket: 'E-Ticket ডাউনলোড কৰক (PDF)',
        please_login_book: 'টিকট বুক কৰিবলৈ লগইন কৰক', registration_success: 'পঞ্জীয়ন সফল! অনুগ্ৰহ কৰি লগইন কৰক।', logged_in: 'সফলভাৱে লগইন হল',
        login_modal_title: 'পুনৰ স্বাগতম', login_modal_desc: 'বুকিং আৰু প্ৰফাইলৰ বাবে লগইন কৰক।', register_modal_title: 'AeroRail ত যোগ দিয়ক',
        register_modal_desc: 'বুকিং আৰম্ভ কৰিবলৈ একাউণ্ট সৃষ্টি কৰক।', username: 'ব্যৱহাৰকাৰীৰ নাম', password: 'পাছৱৰ্ড', dont_have_account: 'একাউণ্ট নাই নেকি?',
        register_link: 'পঞ্জীয়ন', already_have_account: 'আগতে একাউণ্ট আছে নেকি?', login_link: 'লগইন', language: 'ভাষা', create_account: 'একাউণ্ট সৃষ্টি কৰক', my_profile: 'মোৰ প্ৰফাইল', profile_details: 'আপোনাৰ প্ৰফাইলৰ বিৱৰণ', continue: 'আগবাঢ়ক'
    },
    bn: {
        home: 'হোম'