/* STATE & i18n */

export const SUPPORTED_LANGUAGES = [
    { code: 'en', name: 'English' },
    { code: 'as', name: 'অসমীয়া' },
    { code: 'bn', name: 'বাংলা' },
    { code: 'brx', name: 'बड़ो' },
    { code: 'doi', name: 'डोगरी' },
    { code: 'gu', name: 'ગુજરાતી' },
    { code: 'hi', name: 'हिन्दी' },
    { code: 'kn', name: 'ಕನ್ನಡ' },
    { code: 'ks', name: 'کٲشُر' },
    { code: 'kok', name: 'कोंकणी' },
    { code: 'mai', name: 'मैथिली' },
    { code: 'ml', name: 'മലയാളം' },
    { code: 'mni', name: 'মৈতৈলোন্' },
    { code: 'mr', name: 'मराठी' },
    { code: 'ne', name: 'नेपाली' },
    { code: 'or', name: 'ଓଡ଼ିଆ' },
    { code: 'pa', name: 'ਪੰਜਾਬੀ' },
    { code: 'sa', name: 'संस्कृतम्' },
    { code: 'sat', name: 'ᱥᱟᱱᱛᱟᱲᱤ' },
    { code: 'sd', name: 'سنڌي' },
    { code: 'ta', name: 'தமிழ்' },
    { code: 'te', name: 'తెలుగు' },
    { code: 'ur', name: 'اردو' },
];

const en = {
    home: 'Home',
    pnr_status: 'PNR Status',
    live_tracking: 'Live Tracking',
    login: 'Login / Register',
    logout: 'Logout',
    my_account: 'My Account',
    hello: 'Hello',
    book_ticket: 'BOOK TICKET',
    from_station: 'From Station',
    to_station: 'To Station',
    journey_date: 'Journey Date',
    find_trains: 'Find Trains',
    pnr_status_check: 'Check PNR Status',
    pnr_placeholder: 'e.g. 4235678901',
    track_status: 'Track Status',
    search_trains: 'Search Trains',
    passenger_details: 'Passenger Details',
    confirm_pay: 'Confirm & Pay',
    total_amount: 'Total Amount',
    no_trains_found: 'No trains found for this route and date.',
    live_status: 'LIVE STATUS',
    smartest_way: 'The Smartest Way <br/>to Travel by Rail.',
    book_track_pnr: 'Book tickets, track trains in real-time, and get instant updates on PNR status with AeroRail.',
    check_pnr_desc: 'Enter your 10-digit PNR number to get live status.',
    book_now: 'Book Now',
    modify_search: 'Modify Search',
    pnr_status_label: 'PNR Status',
    charts_vacancy: 'Charts / Vacancy',
    train_name_number: 'Train Name / Number',
    boarding_station: 'Boarding Station',
    get_train_chart: 'Get Train Chart',
    enter_city_station: 'Enter City/Station',
    live_train_tracking: 'Live Train Tracking',
    enter_train_number: 'Enter train number to see real-time location and status.',
    track_now: 'Track Now',
    my_bookings: 'My Bookings',
    manage_journeys: 'Manage your upcoming and past journeys.',
    no_bookings: 'No bookings found.',
    ticket_pdf: 'Ticket PDF',
    confirmed: 'CONFIRMED',
    journey_date_label: 'JOURNEY DATE',
    from_label: 'FROM',
    to_label: 'TO',
    download_ticket: 'Download E-Ticket (PDF)',
    please_login_book: 'Please login to book a ticket',
    registration_success: 'Registration successful! Please login.',
    logged_in: 'Logged in successfully',
    login_modal_title: 'Welcome Back',
    login_modal_desc: 'Login to access bookings and profiles.',
    register_modal_title: 'Join AeroRail',
    register_modal_desc: 'Create your account to start booking.',
    username: 'Username',
    password: 'Password',
    dont_have_account: "Don't have an account?",
    register_link: 'Register',
    already_have_account: 'Already have an account?',
    login_link: 'Login',
    language: 'Language',
    create_account: 'Create Account',
    continue: 'Continue'
};

const languageOverrides = {
    as: {
        home: 'ঘৰ', pnr_status: 'PNR স্থিতি', live_tracking: 'লাইভ ট্ৰেকিং', login: 'লগইন / পঞ্জীয়ন', logout: 'লগআউট', my_account: 'মোৰ একাউণ্ট', hello: 'নমস্কাৰ',
        book_ticket: 'টিকট বুক কৰক', from_station: 'প্ৰস্থান ষ্টেচন', to_station: 'গন্তব্য ষ্টেচন', journey_date: 'যাত্ৰাৰ তাৰিখ', find_trains: 'ট্ৰেইন বিচাৰক',
        pnr_status_check: 'PNR স্থিতি চাওক', track_status: 'স্থিতি চাওক', search_trains: 'ট্ৰেইন বিচাৰক', passenger_details: 'যাত্ৰীৰ বিৱৰণ', confirm_pay: 'নিশ্চিত কৰি পে কৰক',
        total_amount: 'মুঠ পৰিমাণ', no_trains_found: 'এই পথ আৰু তাৰিখৰ বাবে ট্ৰেইন পোৱা নগল।', live_status: 'লাইভ স্থিতি',
        smartest_way: 'ৰেলেৰে যাত্ৰাৰ <br/>স্মাৰ্ট উপায়।', book_track_pnr: 'টিকট বুক কৰক, ট্ৰেইন লাইভ ট্ৰেক কৰক, আৰু PNR আপডেট পাওক।',
        check_pnr_desc: 'লাইভ স্থিতিৰ বাবে আপোনাৰ ১০-অংকৰ PNR নম্বৰ লিখক।', book_now: 'এতিয়াই বুক কৰক', pnr_status_label: 'PNR স্থিতি',
        charts_vacancy: 'চাৰ্ট / খালী আসন', train_name_number: 'ট্ৰেইনৰ নাম / নম্বৰ', boarding_station: 'ব’ৰ্ডিং ষ্টেচন', get_train_chart: 'ট্ৰেইন চাৰ্ট পাওক',
        enter_city_station: 'চহৰ/ষ্টেচন লিখক', live_train_tracking: 'লাইভ ট্ৰেইন ট্ৰেকিং', enter_train_number: 'লাইভ অৱস্থান আৰু স্থিতিৰ বাবে ট্ৰেইন নম্বৰ লিখক।',
        track_now: 'এতিয়াই ট্ৰেক কৰক', my_bookings: 'মোৰ বুকিংসমূহ', manage_journeys: 'আপোনাৰ যাত্ৰাসমূহ পৰিচালনা কৰক।', no_bookings: 'কোনো বুকিং পোৱা নগল।',
        ticket_pdf: 'টিকট PDF', confirmed: 'নিশ্চিত', journey_date_label: 'যাত্ৰাৰ তাৰিখ', from_label: 'পৰা', to_label: 'লৈ', download_ticket: 'E-Ticket ডাউনলোড কৰক (PDF)',
        please_login_book: 'টিকট বুক কৰিবলৈ লগইন কৰক', registration_success: 'পঞ্জীয়ন সফল! অনুগ্ৰহ কৰি লগইন কৰক।', logged_in: 'সফলভাৱে লগইন হল',
        login_modal_title: 'পুনৰ স্বাগতম', login_modal_desc: 'বুকিং আৰু প্ৰফাইলৰ বাবে লগইন কৰক।', register_modal_title: 'AeroRail ত যোগ দিয়ক',
        register_modal_desc: 'বুকিং আৰম্ভ কৰিবলৈ একাউণ্ট সৃষ্টি কৰক।', username: 'ব্যৱহাৰকাৰীৰ নাম', password: 'পাছৱৰ্ড', dont_have_account: 'একাউণ্ট নাই নেকি?',
        register_link: 'পঞ্জীয়ন', already_have_account: 'আগতে একাউণ্ট আছে নেকি?', login_link: 'লগইন', language: 'ভাষা', create_account: 'একাউণ্ট সৃষ্টি কৰক', continue: 'আগবাঢ়ক'
    },
    bn: {
        home: 'হোম', pnr_status: 'PNR স্ট্যাটাস', live_tracking: 'লাইভ ট্র্যাকিং', login: 'লগইন / রেজিস্টার', logout: 'লগআউট', my_account: 'আমার অ্যাকাউন্ট', hello: 'নমস্কার',
        book_ticket: 'টিকিট বুক করুন', from_station: 'যাত্রা শুরুর স্টেশন', to_station: 'গন্তব্য স্টেশন', journey_date: 'যাত্রার তারিখ', find_trains: 'ট্রেন খুঁজুন',
        pnr_status_check: 'PNR স্ট্যাটাস দেখুন', track_status: 'স্ট্যাটাস দেখুন', search_trains: 'ট্রেন খুঁজুন', passenger_details: 'যাত্রীর বিবরণ', confirm_pay: 'নিশ্চিত করে পেমেন্ট',
        total_amount: 'মোট টাকা', no_trains_found: 'এই রুট ও তারিখে কোনও ট্রেন পাওয়া যায়নি।', live_status: 'লাইভ স্ট্যাটাস',
        smartest_way: 'রেলে ভ্রমণের <br/>স্মার্ট উপায়।', book_track_pnr: 'টিকিট বুক করুন, ট্রেন লাইভ ট্র্যাক করুন, এবং PNR আপডেট পান।',
        check_pnr_desc: 'লাইভ স্ট্যাটাস পেতে আপনার ১০ অঙ্কের PNR নম্বর লিখুন।', book_now: 'এখনই বুক করুন', pnr_status_label: 'PNR স্ট্যাটাস',
        charts_vacancy: 'চার্ট / খালি আসন', train_name_number: 'ট্রেনের নাম / নম্বর', boarding_station: 'বোর্ডিং স্টেশন', get_train_chart: 'ট্রেন চার্ট পান',
        enter_city_station: 'শহর/স্টেশন লিখুন', live_train_tracking: 'লাইভ ট্রেন ট্র্যাকিং', enter_train_number: 'লাইভ অবস্থান ও স্ট্যাটাস দেখতে ট্রেন নম্বর লিখুন।',
        track_now: 'এখন ট্র্যাক করুন', my_bookings: 'আমার বুকিং', manage_journeys: 'আপনার যাত্রা পরিচালনা করুন।', no_bookings: 'কোনও বুকিং পাওয়া যায়নি।',
        ticket_pdf: 'টিকিট PDF', confirmed: 'নিশ্চিত', journey_date_label: 'যাত্রার তারিখ', from_label: 'থেকে', to_label: 'পর্যন্ত', download_ticket: 'E-Ticket ডাউনলোড করুন (PDF)',
        please_login_book: 'টিকিট বুক করতে লগইন করুন', registration_success: 'রেজিস্ট্রেশন সফল! অনুগ্রহ করে লগইন করুন।', logged_in: 'সফলভাবে লগইন হয়েছে',
        login_modal_title: 'আবার স্বাগতম', login_modal_desc: 'বুকিং ও প্রোফাইলে যেতে লগইন করুন।', register_modal_title: 'AeroRail-এ যোগ দিন',
        register_modal_desc: 'বুকিং শুরু করতে অ্যাকাউন্ট তৈরি করুন।', username: 'ব্যবহারকারীর নাম', password: 'পাসওয়ার্ড', dont_have_account: 'অ্যাকাউন্ট নেই?',
        register_link: 'রেজিস্টার', already_have_account: 'আগে থেকেই অ্যাকাউন্ট আছে?', login_link: 'লগইন', language: 'ভাষা', create_account: 'অ্যাকাউন্ট তৈরি করুন', continue: 'চালিয়ে যান'
    },
    brx: {
        home: 'होम', pnr_status: 'PNR थासारि', live_tracking: 'लाइभ ट्रेकिंग', login: 'लगइन / रेजिस्टर', logout: 'लगआउट', my_account: 'आंनि एकाउन्ट',
        hello: 'खुलुमबाय', book_ticket: 'टिकट बुक खालाम', from_station: 'निफ्राय स्टेशन', to_station: 'सिम स्टेशन', journey_date: 'दावबायनाय अक्टो',
        find_trains: 'ट्रेन नागिर', pnr_status_check: 'PNR थासारि नाय', track_status: 'थासारि नाय', search_trains: 'ट्रेन नागिर', passenger_details: 'दावबायग्रानि बिबुंथि',
        confirm_pay: 'थि खालाम आरो पे खालाम', total_amount: 'गासै रां', no_trains_found: 'बे रुट आरो अक्टोआव ट्रेन मोनाखै।', live_status: 'लाइभ थासारि',
        smartest_way: 'रेलजों दावबायनायनि <br/>स्मार्ट राहा।', book_track_pnr: 'टिकट बुक खालाम, ट्रेन ट्रेक खालाम आरो PNR अपडेट ला।',
        check_pnr_desc: 'लाइभ थासारिनि थाखाय 10 अंक PNR नम्बर हो।', book_now: 'दानो बुक खालाम', pnr_status_label: 'PNR थासारि',
        charts_vacancy: 'चार्ट / खालि सिट', train_name_number: 'ट्रेन मुं / नम्बर', boarding_station: 'बर्डिंग स्टेशन', get_train_chart: 'ट्रेन चार्ट ला',
        enter_city_station: 'सहर/स्टेशन हो', live_train_tracking: 'लाइभ ट्रेन ट्रेकिंग', enter_train_number: 'थासारि नायनो ट्रेन नम्बर हो।',
        track_now: 'दानो ट्रेक', my_bookings: 'आंनि बुकिंग', manage_journeys: 'आंनि दावबायनाय सामलाय।', no_bookings: 'बुकिंग गैया।',
        ticket_pdf: 'टिकट PDF', confirmed: 'थि खालामबाय', journey_date_label: 'दावबायनाय अक्टो', from_label: 'निफ्राय', to_label: 'सिम',
        download_ticket: 'E-Ticket डाउनलोड खालाम (PDF)', please_login_book: 'टिकट बुक खालामनो लगइन खालाम', language: 'राव', username: 'युजार मुं',
        password: 'पासवर्ड', login_link: 'लगइन', register_link: 'रेजिस्टर'
    },
    doi: {
        home: 'होम', pnr_status: 'PNR स्थिति', live_tracking: 'लाइव ट्रैकिंग', login: 'लॉगिन / रजिस्टर', logout: 'लॉगआउट', my_account: 'मेरा खाता', hello: 'नमस्कार',
        book_ticket: 'टिकट बुक करो', from_station: 'किस स्टेशन थमां', to_station: 'किस स्टेशन तगर', journey_date: 'यात्रा दी तारीख', find_trains: 'ट्रेनां खोजो',
        pnr_status_check: 'PNR स्थिति जांचो', track_status: 'स्थिति जांचो', search_trains: 'ट्रेनां खोजो', passenger_details: 'यात्री विवरण', confirm_pay: 'पुष्टि ते भुगतान',
        total_amount: 'कुल रकम', no_trains_found: 'इस रूट ते तारीख आस्तै कोई ट्रेन नेई मिली।', live_status: 'लाइव स्थिति',
        smartest_way: 'रेल कन्नै यात्रा दा <br/>स्मार्ट तरीका।', book_track_pnr: 'टिकट बुक करो, ट्रेन लाइव ट्रैक करो, ते PNR अपडेट लो।',
        check_pnr_desc: 'लाइव स्थिति आस्तै अपना 10 अंकीय PNR नंबर दर्ज करो।', book_now: 'हुण बुक करो', pnr_status_label: 'PNR स्थिति',
        charts_vacancy: 'चार्ट / खाली सीट', train_name_number: 'ट्रेन दा नां / नंबर', boarding_station: 'बोर्डिंग स्टेशन', get_train_chart: 'ट्रेन चार्ट लो',
        enter_city_station: 'शहर/स्टेशन दर्ज करो', live_train_tracking: 'लाइव ट्रेन ट्रैकिंग', enter_train_number: 'लाइव स्थान ते स्थिति आस्तै ट्रेन नंबर दर्ज करो।',
        track_now: 'हुण ट्रैक करो', my_bookings: 'मेरी बुकिंगां', manage_journeys: 'अपनी यात्रां संभालो।', no_bookings: 'कोई बुकिंग नेई मिली।',
        ticket_pdf: 'टिकट PDF', confirmed: 'पुष्ट', journey_date_label: 'यात्रा दी तारीख', from_label: 'थमां', to_label: 'तगर', download_ticket: 'E-Ticket डाउनलोड करो (PDF)',
        please_login_book: 'टिकट बुक करने आस्तै लॉगिन करो', registration_success: 'रजिस्ट्रेशन सफल! कृपा लॉगिन करो।', logged_in: 'सफलतापूर्वक लॉगिन होया',
        login_modal_title: 'स्वागतम्', login_modal_desc: 'बुकिंग ते प्रोफाइल आस्तै लॉगिन करो।', register_modal_title: 'AeroRail च शामल होओ',
        register_modal_desc: 'बुकिंग शुरू करने आस्तै खाता बनाओ।', username: 'यूजरनेम', password: 'पासवर्ड', dont_have_account: 'खाता नेई ऐ?',
        register_link: 'रजिस्टर', already_have_account: 'पहले थमां खाता ऐ?', login_link: 'लॉगिन', language: 'भाषा', create_account: 'खाता बनाओ', continue: 'जारी रखो'
    },
    gu: {
        home: 'હોમ', pnr_status: 'PNR સ્થિતિ', live_tracking: 'લાઈવ ટ્રેકિંગ', login: 'લોગિન / રજિસ્ટર', logout: 'લોગઆઉટ', my_account: 'મારું ખાતું', hello: 'નમસ્તે',
        book_ticket: 'ટિકિટ બુક કરો', from_station: 'પ્રસ્થાન સ્ટેશન', to_station: 'ગંતવ્ય સ્ટેશન', journey_date: 'મુસાફરીની તારીખ', find_trains: 'ટ્રેનો શોધો',
        pnr_status_check: 'PNR સ્થિતિ તપાસો', track_status: 'સ્થિતિ તપાસો', search_trains: 'ટ્રેનો શોધો', passenger_details: 'મુસાફર વિગતો', confirm_pay: 'ખાતરી કરો અને ચૂકવો',
        total_amount: 'કુલ રકમ', no_trains_found: 'આ રૂટ અને તારીખ માટે કોઈ ટ્રેન મળી નથી.', live_status: 'લાઈવ સ્થિતિ',
        smartest_way: 'રેલ મુસાફરીનો <br/>સ્માર્ટ રસ્તો.', book_track_pnr: 'ટિકિટ બુક કરો, ટ્રેનો લાઈવ ટ્રેક કરો અને PNR અપડેટ મેળવો.',
        check_pnr_desc: 'લાઈવ સ્થિતિ માટે તમારો 10 અંકનો PNR નંબર દાખલ કરો.', book_now: 'હમણાં બુક કરો', pnr_status_label: 'PNR સ્થિતિ',
        charts_vacancy: 'ચાર્ટ / ખાલી બેઠકો', train_name_number: 'ટ્રેન નામ / નંબર', boarding_station: 'બોર્ડિંગ સ્ટેશન', get_train_chart: 'ટ્રેન ચાર્ટ મેળવો',
        enter_city_station: 'શહેર/સ્ટેશન દાખલ કરો', live_train_tracking: 'લાઈવ ટ્રેન ટ્રેકિંગ', enter_train_number: 'લાઈવ સ્થાન અને સ્થિતિ માટે ટ્રેન નંબર દાખલ કરો.',
        track_now: 'હમણાં ટ્રેક કરો', my_bookings: 'મારી બુકિંગ્સ', manage_journeys: 'તમારી મુસાફરીઓ સંચાલિત કરો.', no_bookings: 'કોઈ બુકિંગ મળી નથી.',
        ticket_pdf: 'ટિકિટ PDF', confirmed: 'ખાતરી થયેલ', journey_date_label: 'મુસાફરીની તારીખ', from_label: 'થી', to_label: 'સુધી', download_ticket: 'E-Ticket ડાઉનલોડ કરો (PDF)',
        please_login_book: 'ટિકિટ બુક કરવા લોગિન કરો', registration_success: 'રજિસ્ટ્રેશન સફળ! કૃપા કરીને લોગિન કરો.', logged_in: 'સફળતાપૂર્વક લોગિન થયું',
        login_modal_title: 'ફરી સ્વાગત છે', login_modal_desc: 'બુકિંગ અને પ્રોફાઇલ માટે લોગિન કરો.', register_modal_title: 'AeroRail માં જોડાઓ',
        register_modal_desc: 'બુકિંગ શરૂ કરવા ખાતું બનાવો.', username: 'વપરાશકર્તા નામ', password: 'પાસવર્ડ', dont_have_account: 'ખાતું નથી?',
        register_link: 'રજિસ્ટર', already_have_account: 'પહેલેથી ખાતું છે?', login_link: 'લોગિન', language: 'ભાષા', create_account: 'ખાતું બનાવો', continue: 'ચાલુ રાખો'
    },
    hi: {
        home: 'होम', pnr_status: 'PNR स्थिति', live_tracking: 'लाइव ट्रैकिंग', login: 'लॉगिन / रजिस्टर', logout: 'लॉगआउट', my_account: 'मेरा खाता', hello: 'नमस्ते',
        book_ticket: 'टिकट बुक करें', from_station: 'प्रस्थान स्टेशन', to_station: 'गंतव्य स्टेशन', journey_date: 'यात्रा की तारीख', find_trains: 'ट्रेन खोजें',
        pnr_status_check: 'PNR स्थिति जांचें', track_status: 'स्थिति जांचें', search_trains: 'ट्रेन खोजें', passenger_details: 'यात्री विवरण', confirm_pay: 'पुष्टि करें और भुगतान करें',
        total_amount: 'कुल राशि', no_trains_found: 'इस रूट और तारीख के लिए कोई ट्रेन नहीं मिली।', live_status: 'लाइव स्थिति',
        smartest_way: 'रेल यात्रा का <br/>सबसे स्मार्ट तरीका।', book_track_pnr: 'टिकट बुक करें, ट्रेनें लाइव ट्रैक करें, और PNR अपडेट पाएं।',
        check_pnr_desc: 'लाइव स्थिति के लिए अपना 10 अंकों का PNR नंबर दर्ज करें।', book_now: 'अभी बुक करें', modify_search: 'खोज बदलें', pnr_status_label: 'PNR स्थिति',
        charts_vacancy: 'चार्ट / रिक्तता', train_name_number: 'ट्रेन नाम / नंबर', boarding_station: 'बोर्डिंग स्टेशन', get_train_chart: 'ट्रेन चार्ट देखें',
        enter_city_station: 'शहर/स्टेशन दर्ज करें', live_train_tracking: 'लाइव ट्रेन ट्रैकिंग', enter_train_number: 'लाइव स्थान और स्थिति देखने के लिए ट्रेन नंबर दर्ज करें।',
        track_now: 'अभी ट्रैक करें', my_bookings: 'मेरी बुकिंग', manage_journeys: 'अपनी यात्राएं प्रबंधित करें।', no_bookings: 'कोई बुकिंग नहीं मिली।',
        ticket_pdf: 'टिकट PDF', confirmed: 'पुष्ट', journey_date_label: 'यात्रा की तारीख', from_label: 'से', to_label: 'तक', download_ticket: 'E-Ticket डाउनलोड करें (PDF)',
        please_login_book: 'टिकट बुक करने के लिए लॉगिन करें', registration_success: 'पंजीकरण सफल! कृपया लॉगिन करें।', logged_in: 'सफलतापूर्वक लॉगिन हुआ',
        login_modal_title: 'वापस स्वागत है', login_modal_desc: 'बुकिंग और प्रोफाइल के लिए लॉगिन करें।', register_modal_title: 'AeroRail से जुड़ें',
        register_modal_desc: 'बुकिंग शुरू करने के लिए खाता बनाएं।', username: 'उपयोगकर्ता नाम', password: 'पासवर्ड', dont_have_account: 'खाता नहीं है?',
        register_link: 'रजिस्टर', already_have_account: 'पहले से खाता है?', login_link: 'लॉगिन', language: 'भाषा', create_account: 'खाता बनाएं', continue: 'जारी रखें'
    },
    kn: {
        home: 'ಮುಖಪುಟ', pnr_status: 'PNR ಸ್ಥಿತಿ', live_tracking: 'ಲೈವ್ ಟ್ರ್ಯಾಕಿಂಗ್', login: 'ಲಾಗಿನ್ / ನೋಂದಣಿ', logout: 'ಲಾಗ್ಔಟ್', my_account: 'ನನ್ನ ಖಾತೆ', hello: 'ನಮಸ್ಕಾರ',
        book_ticket: 'ಟಿಕೆಟ್ ಬುಕ್ ಮಾಡಿ', from_station: 'ಪ್ರಾರಂಭ ನಿಲ್ದಾಣ', to_station: 'ಗಮ್ಯ ನಿಲ್ದಾಣ', journey_date: 'ಪ್ರಯಾಣ ದಿನಾಂಕ', find_trains: 'ರೈಲುಗಳನ್ನು ಹುಡುಕಿ',
        pnr_status_check: 'PNR ಸ್ಥಿತಿ ಪರಿಶೀಲಿಸಿ', track_status: 'ಸ್ಥಿತಿ ಪರಿಶೀಲಿಸಿ', search_trains: 'ರೈಲುಗಳನ್ನು ಹುಡುಕಿ', passenger_details: 'ಪ್ರಯಾಣಿಕರ ವಿವರಗಳು',
        confirm_pay: 'ದೃಢೀಕರಿಸಿ ಮತ್ತು ಪಾವತಿಸಿ', total_amount: 'ಒಟ್ಟು ಮೊತ್ತ', no_trains_found: 'ಈ ಮಾರ್ಗ ಮತ್ತು ದಿನಾಂಕಕ್ಕೆ ರೈಲು ಸಿಗಲಿಲ್ಲ.', live_status: 'ಲೈವ್ ಸ್ಥಿತಿ',
        smartest_way: 'ರೈಲಿನಲ್ಲಿ ಪ್ರಯಾಣಿಸುವ <br/>ಸ್ಮಾರ್ಟ್ ಮಾರ್ಗ.', book_track_pnr: 'ಟಿಕೆಟ್ ಬುಕ್ ಮಾಡಿ, ರೈಲುಗಳನ್ನು ಲೈವ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ, ಮತ್ತು PNR ಅಪ್ಡೇಟ್ ಪಡೆಯಿರಿ.',
        check_pnr_desc: 'ಲೈವ್ ಸ್ಥಿತಿಗಾಗಿ ನಿಮ್ಮ 10 ಅಂಕಿಯ PNR ಸಂಖ್ಯೆ ನಮೂದಿಸಿ.', book_now: 'ಈಗ ಬುಕ್ ಮಾಡಿ', pnr_status_label: 'PNR ಸ್ಥಿತಿ',
        charts_vacancy: 'ಚಾರ್ಟ್ / ಖಾಲಿ ಆಸನ', train_name_number: 'ರೈಲು ಹೆಸರು / ಸಂಖ್ಯೆ', boarding_station: 'ಬೋರ್ಡಿಂಗ್ ನಿಲ್ದಾಣ', get_train_chart: 'ರೈಲು ಚಾರ್ಟ್ ಪಡೆಯಿರಿ',
        enter_city_station: 'ನಗರ/ನಿಲ್ದಾಣ ನಮೂದಿಸಿ', live_train_tracking: 'ಲೈವ್ ರೈಲು ಟ್ರ್ಯಾಕಿಂಗ್', enter_train_number: 'ಲೈವ್ ಸ್ಥಳ ಮತ್ತು ಸ್ಥಿತಿಗಾಗಿ ರೈಲು ಸಂಖ್ಯೆ ನಮೂದಿಸಿ.',
        track_now: 'ಈಗ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ', my_bookings: 'ನನ್ನ ಬುಕ್ಕಿಂಗ್‌ಗಳು', manage_journeys: 'ನಿಮ್ಮ ಪ್ರಯಾಣಗಳನ್ನು ನಿರ್ವಹಿಸಿ.', no_bookings: 'ಯಾವುದೇ ಬುಕ್ಕಿಂಗ್ ಸಿಗಲಿಲ್ಲ.',
        ticket_pdf: 'ಟಿಕೆಟ್ PDF', confirmed: 'ದೃಢೀಕೃತ', journey_date_label: 'ಪ್ರಯಾಣ ದಿನಾಂಕ', from_label: 'ಇಂದ', to_label: 'ವರೆಗೆ', download_ticket: 'E-Ticket ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ (PDF)',
        please_login_book: 'ಟಿಕೆಟ್ ಬುಕ್ ಮಾಡಲು ಲಾಗಿನ್ ಮಾಡಿ', registration_success: 'ನೋಂದಣಿ ಯಶಸ್ವಿ! ದಯವಿಟ್ಟು ಲಾಗಿನ್ ಮಾಡಿ.', logged_in: 'ಯಶಸ್ವಿಯಾಗಿ ಲಾಗಿನ್ ಆಯಿತು',
        login_modal_title: 'ಮತ್ತೆ ಸ್ವಾಗತ', login_modal_desc: 'ಬುಕ್ಕಿಂಗ್ ಮತ್ತು ಪ್ರೊಫೈಲ್‌ಗಳಿಗೆ ಲಾಗಿನ್ ಮಾಡಿ.', register_modal_title: 'AeroRail ಗೆ ಸೇರಿ',
        register_modal_desc: 'ಬುಕ್ಕಿಂಗ್ ಆರಂಭಿಸಲು ಖಾತೆ ರಚಿಸಿ.', username: 'ಬಳಕೆದಾರ ಹೆಸರು', password: 'ಪಾಸ್‌ವರ್ಡ್', dont_have_account: 'ಖಾತೆ ಇಲ್ಲವೇ?',
        register_link: 'ನೋಂದಣಿ', already_have_account: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?', login_link: 'ಲಾಗಿನ್', language: 'ಭಾಷೆ', create_account: 'ಖಾತೆ ರಚಿಸಿ', continue: 'ಮುಂದುವರಿಸಿ'
    },
    ks: {
        home: 'ہوم', pnr_status: 'PNR حالت', live_tracking: 'لائیو ٹریکنگ', login: 'لاگ اِن / رجسٹر', logout: 'لاگ آؤٹ', my_account: 'میرا اکاؤنٹ', hello: 'آداب',
        book_ticket: 'ٹکٹ بک کریو', from_station: 'شروعاتی اسٹیشن', to_station: 'منزل اسٹیشن', journey_date: 'سفر تاریخ', find_trains: 'ٹرین تلاش کریو',
        pnr_status_check: 'PNR حالت دیکھو', track_status: 'حالت دیکھو', search_trains: 'ٹرین تلاش کریو', passenger_details: 'مسافر تفصیل', confirm_pay: 'تصدیق تہ ادائیگی',
        total_amount: 'کل رقم', no_trains_found: 'اس روٹ تہ تاریخس پیٹھ کانہہ ٹرین نہ ملی۔', live_status: 'لائیو حالت',
        smartest_way: 'ریل سفرُک <br/>اسمارٹ طریقہ۔', book_track_pnr: 'ٹکٹ بک کریو، ٹرین لائیو ٹریک کریو، تہ PNR اپڈیٹ حاصل کریو۔',
        check_pnr_desc: 'لائیو حالت باپت 10 ہندسہ PNR نمبر درج کریو۔', book_now: 'وُنہ بک کریو', pnr_status_label: 'PNR حالت',
        charts_vacancy: 'چارٹ / خالی سیٹ', train_name_number: 'ٹرین نام / نمبر', boarding_station: 'بورڈنگ اسٹیشن', get_train_chart: 'ٹرین چارٹ حاصل کریو',
        enter_city_station: 'شہر/اسٹیشن درج کریو', live_train_tracking: 'لائیو ٹرین ٹریکنگ', enter_train_number: 'لائیو مقام تہ حالت باپت ٹرین نمبر درج کریو۔',
        track_now: 'وُنہ ٹریک کریو', my_bookings: 'میری بکنگ', manage_journeys: 'پنُن سفر سنبھالِو۔', no_bookings: 'کانہہ بکنگ نہ ملی۔',
        ticket_pdf: 'ٹکٹ PDF', confirmed: 'تصدیق شدہ', journey_date_label: 'سفر تاریخ', from_label: 'سے', to_label: 'تک', download_ticket: 'E-Ticket ڈاؤنلوڈ کریو (PDF)',
        please_login_book: 'ٹکٹ بک کرنہ باپت لاگ اِن کریو', language: 'زبان', username: 'یوزر نام', password: 'پاس ورڈ', login_link: 'لاگ اِن', register_link: 'رجسٹر'
    },
    kok: {
        home: 'होम', pnr_status: 'PNR स्थिती', live_tracking: 'लाइव ट्रॅकिंग', login: 'लॉगिन / नोंदणी', logout: 'लॉगआउट', my_account: 'माझें खातें', hello: 'नमस्कार',
        book_ticket: 'तिकीट बुक करात', from_station: 'सुरवातीचें स्टेशन', to_station: 'गंतव्य स्टेशन', journey_date: 'प्रवासाची तारीख', find_trains: 'रेल्वे सोदात',
        pnr_status_check: 'PNR स्थिती तपासात', track_status: 'स्थिती तपासात', search_trains: 'रेल्वे सोदात', passenger_details: 'प्रवासी तपशील', confirm_pay: 'निश्चित करून पे करात',
        total_amount: 'एकूण रक्कम', no_trains_found: 'ह्या मार्गार आनी तारखेक रेल्वे मेळूंक ना।', live_status: 'लाइव स्थिती',
        smartest_way: 'रेल्वेन प्रवासाचो <br/>स्मार्ट मार्ग।', book_track_pnr: 'तिकीट बुक करात, रेल्वे लाइव ट्रॅक करात, आनी PNR अपडेट मेळयात।',
        check_pnr_desc: 'लाइव स्थिती खातीर 10 अंकी PNR नंबर घालात।', book_now: 'आतां बुक करात', pnr_status_label: 'PNR स्थिती',
        charts_vacancy: 'चार्ट / रिकामी जागा', train_name_number: 'रेल्वे नाव / नंबर', boarding_station: 'बोर्डिंग स्टेशन', get_train_chart: 'रेल्वे चार्ट मेळयात',
        enter_city_station: 'शार/स्टेशन घालात', live_train_tracking: 'लाइव रेल्वे ट्रॅकिंग', enter_train_number: 'लाइव ठिकाण आनी स्थिती खातीर रेल्वे नंबर घालात।',
        track_now: 'आतां ट्रॅक करात', my_bookings: 'माझी बुकिंग', manage_journeys: 'तुमचे प्रवास सांभाळात।', no_bookings: 'बुकिंग मेळूंक ना।',
        ticket_pdf: 'तिकीट PDF', confirmed: 'निश्चित', journey_date_label: 'प्रवासाची तारीख', from_label: 'पासून', to_label: 'पर्यंत', download_ticket: 'E-Ticket डाउनलोड करात (PDF)',
        please_login_book: 'तिकीट बुक करपाक लॉगिन करात', language: 'भास', username: 'वापरपी नाव', password: 'पासवर्ड', login_link: 'लॉगिन', register_link: 'नोंदणी'
    },
    mai: {
        home: 'होम', pnr_status: 'PNR स्थिति', live_tracking: 'लाइव ट्रैकिंग', login: 'लॉगिन / रजिस्टर', logout: 'लॉगआउट', my_account: 'हमर खाता', hello: 'नमस्कार',
        book_ticket: 'टिकट बुक करू', from_station: 'प्रस्थान स्टेशन', to_station: 'गंतव्य स्टेशन', journey_date: 'यात्रा तिथि', find_trains: 'ट्रेन खोजू',
        pnr_status_check: 'PNR स्थिति देखू', track_status: 'स्थिति देखू', search_trains: 'ट्रेन खोजू', passenger_details: 'यात्री विवरण', confirm_pay: 'पुष्टि करू आ भुगतान करू',
        total_amount: 'कुल राशि', no_trains_found: 'एहि रूट आ तिथि पर कोनो ट्रेन नहि भेटल।', live_status: 'लाइव स्थिति',
        smartest_way: 'रेल यात्रा केर <br/>स्मार्ट तरीका।', book_track_pnr: 'टिकट बुक करू, ट्रेन लाइव ट्रैक करू, आ PNR अपडेट पाउ।',
        check_pnr_desc: 'लाइव स्थिति लेल अपन 10 अंकक PNR नंबर दर्ज करू।', book_now: 'एखन बुक करू', pnr_status_label: 'PNR स्थिति',
        charts_vacancy: 'चार्ट / खाली सीट', train_name_number: 'ट्रेन नाम / नंबर', boarding_station: 'बोर्डिंग स्टेशन', get_train_chart: 'ट्रेन चार्ट पाउ',
        enter_city_station: 'शहर/स्टेशन दर्ज करू', live_train_tracking: 'लाइव ट्रेन ट्रैकिंग', enter_train_number: 'लाइव स्थान आ स्थिति लेल ट्रेन नंबर दर्ज करू।',
        track_now: 'एखन ट्रैक करू', my_bookings: 'हमर बुकिंग', manage_journeys: 'अपन यात्रा प्रबंधित करू।', no_bookings: 'कोनो बुकिंग नहि भेटल।',
        ticket_pdf: 'टिकट PDF', confirmed: 'पुष्ट', journey_date_label: 'यात्रा तिथि', from_label: 'सँ', to_label: 'धरि', download_ticket: 'E-Ticket डाउनलोड करू (PDF)',
        please_login_book: 'टिकट बुक करबाक लेल लॉगिन करू', language: 'भाषा', username: 'उपयोगकर्ता नाम', password: 'पासवर्ड', login_link: 'लॉगिन', register_link: 'रजिस्टर'
    },
    ml: {
        home: 'ഹോം', pnr_status: 'PNR നില', live_tracking: 'ലൈവ് ട്രാക്കിംഗ്', login: 'ലോഗിൻ / രജിസ്റ്റർ', logout: 'ലോഗ്ഔട്ട്', my_account: 'എന്റെ അക്കൗണ്ട്', hello: 'നമസ്കാരം',
        book_ticket: 'ടിക്കറ്റ് ബുക്ക് ചെയ്യുക', from_station: 'പുറപ്പെടുന്ന സ്റ്റേഷൻ', to_station: 'ലക്ഷ്യ സ്റ്റേഷൻ', journey_date: 'യാത്രാ തീയതി', find_trains: 'ട്രെയിനുകൾ കണ്ടെത്തുക',
        pnr_status_check: 'PNR നില പരിശോധിക്കുക', track_status: 'നില പരിശോധിക്കുക', search_trains: 'ട്രെയിനുകൾ തിരയുക', passenger_details: 'യാത്രക്കാരുടെ വിവരങ്ങൾ',
        confirm_pay: 'സ്ഥിരീകരിച്ച് പണമടയ്ക്കുക', total_amount: 'ആകെ തുക', no_trains_found: 'ഈ റൂട്ടിലും തീയതിയിലും ട്രെയിൻ കണ്ടെത്തിയില്ല.', live_status: 'ലൈവ് നില',
        smartest_way: 'റെയിൽ യാത്രയുടെ <br/>സ്മാർട്ട് മാർഗം.', book_track_pnr: 'ടിക്കറ്റ് ബുക്ക് ചെയ്യുക, ട്രെയിനുകൾ ലൈവ് ട്രാക്ക് ചെയ്യുക, PNR അപ്ഡേറ്റ് നേടുക.',
        check_pnr_desc: 'ലൈവ് നിലയ്ക്കായി നിങ്ങളുടെ 10 അക്ക PNR നമ്പർ നൽകുക.', book_now: 'ഇപ്പോൾ ബുക്ക് ചെയ്യുക', pnr_status_label: 'PNR നില',
        charts_vacancy: 'ചാർട്ട് / ഒഴിവ്', train_name_number: 'ട്രെയിൻ പേര് / നമ്പർ', boarding_station: 'ബോർഡിംഗ് സ്റ്റേഷൻ', get_train_chart: 'ട്രെയിൻ ചാർട്ട് നേടുക',
        enter_city_station: 'നഗരം/സ്റ്റേഷൻ നൽകുക', live_train_tracking: 'ലൈവ് ട്രെയിൻ ട്രാക്കിംഗ്', enter_train_number: 'ലൈവ് സ്ഥാനം, നില കാണാൻ ട്രെയിൻ നമ്പർ നൽകുക.',
        track_now: 'ഇപ്പോൾ ട്രാക്ക് ചെയ്യുക', my_bookings: 'എന്റെ ബുക്കിംഗുകൾ', manage_journeys: 'നിങ്ങളുടെ യാത്രകൾ നിയന്ത്രിക്കുക.', no_bookings: 'ബുക്കിംഗ് കണ്ടെത്തിയില്ല.',
        ticket_pdf: 'ടിക്കറ്റ് PDF', confirmed: 'സ്ഥിരീകരിച്ചു', journey_date_label: 'യാത്രാ തീയതി', from_label: 'നിന്ന്', to_label: 'വരെ', download_ticket: 'E-Ticket ഡൗൺലോഡ് ചെയ്യുക (PDF)',
        please_login_book: 'ടിക്കറ്റ് ബുക്ക് ചെയ്യാൻ ലോഗിൻ ചെയ്യുക', registration_success: 'രജിസ്ട്രേഷൻ വിജയിച്ചു! ദയവായി ലോഗിൻ ചെയ്യുക.', logged_in: 'വിജയകരമായി ലോഗിൻ ചെയ്തു',
        login_modal_title: 'വീണ്ടും സ്വാഗതം', login_modal_desc: 'ബുക്കിംഗുകൾക്കും പ്രൊഫൈലിനും ലോഗിൻ ചെയ്യുക.', register_modal_title: 'AeroRail-ൽ ചേരുക',
        register_modal_desc: 'ബുക്കിംഗ് തുടങ്ങാൻ അക്കൗണ്ട് സൃഷ്ടിക്കുക.', username: 'ഉപയോക്തൃനാമം', password: 'പാസ്‌വേഡ്', dont_have_account: 'അക്കൗണ്ട് ഇല്ലേ?',
        register_link: 'രജിസ്റ്റർ', already_have_account: 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?', login_link: 'ലോഗിൻ', language: 'ഭാഷ', create_account: 'അക്കൗണ്ട് സൃഷ്ടിക്കുക', continue: 'തുടരുക'
    },
    mni: {
        home: 'হোম', pnr_status: 'PNR ফিবম', live_tracking: 'লাইভ ত্রেকিং', login: 'লগইন / রেজিস্তর', logout: 'লগআউত', my_account: 'ঐগী একাউন্ত', hello: 'খুরুমজরি',
        book_ticket: 'তিকেত বুক তৌ', from_station: 'হৌরকফম স্তেশন', to_station: 'যৌফম স্তেশন', journey_date: 'খোঙচৎ নুমিৎ', find_trains: 'ত্রেন থিবা',
        pnr_status_check: 'PNR ফিবম য়েং', track_status: 'ফিবম য়েং', search_trains: 'ত্রেন থিবা', passenger_details: 'মীশিংগী অচুম্বা', confirm_pay: 'কনফার্ম অমসুং পে',
        total_amount: 'অপুনবা শেনফম', no_trains_found: 'মসিগী রুত অমসুং নুমিৎদা ত্রেন ফংদ্রে।', live_status: 'লাইভ ফিবম',
        smartest_way: 'রেলগী <br/>স্মার্ট খোঙচৎ।', book_track_pnr: 'তিকেত বুক তৌ, ত্রেন লাইভ ত্রেক তৌ, অমসুং PNR আপদেত ফংউ।',
        check_pnr_desc: 'লাইভ ফিবমগীদমক 10 ডিজিত PNR নম্বর হাপচিনউ।', book_now: 'হৌজিক বুক তৌ', pnr_status_label: 'PNR ফিবম',
        charts_vacancy: 'চার্ট / খালি সিট', train_name_number: 'ত্রেন মিং / নম্বর', boarding_station: 'বোর্ডিং স্তেশন', get_train_chart: 'ত্রেন চার্ট লৌ',
        enter_city_station: 'সহর/স্তেশন হাপচিনউ', live_train_tracking: 'লাইভ ত্রেন ত্রেকিং', enter_train_number: 'লাইভ মফম অমসুং ফিবমগীদমক ত্রেন নম্বর হাপচিনউ।',
        track_now: 'হৌজিক ত্রেক তৌ', my_bookings: 'ঐগী বুকিং', manage_journeys: 'নহাক্কী খোঙচৎ মেনেজ তৌ।', no_bookings: 'বুকিং ফংদ্রে।',
        ticket_pdf: 'তিকেত PDF', confirmed: 'কনফার্ম', journey_date_label: 'খোঙচৎ নুমিৎ', from_label: 'দগী', to_label: 'ফাওবা', download_ticket: 'E-Ticket দাউনলোদ তৌ (PDF)',
        please_login_book: 'তিকেত বুক তৌনবা লগইন তৌ', language: 'লোন', username: 'ইউজর মিং', password: 'পাসৱার্দ', login_link: 'লগইন', register_link: 'রেজিস্তর'
    },
    mr: {
        home: 'होम', pnr_status: 'PNR स्थिती', live_tracking: 'लाईव्ह ट्रॅकिंग', login: 'लॉगिन / नोंदणी', logout: 'लॉगआउट', my_account: 'माझे खाते', hello: 'नमस्कार',
        book_ticket: 'तिकीट बुक करा', from_station: 'प्रस्थान स्टेशन', to_station: 'गंतव्य स्टेशन', journey_date: 'प्रवासाची तारीख', find_trains: 'ट्रेन शोधा',
        pnr_status_check: 'PNR स्थिती तपासा', track_status: 'स्थिती तपासा', search_trains: 'ट्रेन शोधा', passenger_details: 'प्रवासी तपशील', confirm_pay: 'पुष्टी करून पैसे भरा',
        total_amount: 'एकूण रक्कम', no_trains_found: 'या मार्गासाठी आणि तारखेसाठी कोणतीही ट्रेन आढळली नाही.', live_status: 'लाईव्ह स्थिती',
        smartest_way: 'रेल्वे प्रवासाचा <br/>स्मार्ट मार्ग.', book_track_pnr: 'तिकीट बुक करा, ट्रेन लाईव्ह ट्रॅक करा आणि PNR अपडेट मिळवा.',
        check_pnr_desc: 'लाईव्ह स्थितीसाठी तुमचा 10 अंकी PNR नंबर टाका.', book_now: 'आता बुक करा', pnr_status_label: 'PNR स्थिती',
        charts_vacancy: 'चार्ट / रिक्त जागा', train_name_number: 'ट्रेन नाव / नंबर', boarding_station: 'बोर्डिंग स्टेशन', get_train_chart: 'ट्रेन चार्ट मिळवा',
        enter_city_station: 'शहर/स्टेशन टाका', live_train_tracking: 'लाईव्ह ट्रेन ट्रॅकिंग', enter_train_number: 'लाईव्ह स्थान आणि स्थितीसाठी ट्रेन नंबर टाका.',
        track_now: 'आता ट्रॅक करा', my_bookings: 'माझी बुकिंग', manage_journeys: 'तुमचे प्रवास व्यवस्थापित करा.', no_bookings: 'कोणतीही बुकिंग आढळली नाही.',
        ticket_pdf: 'तिकीट PDF', confirmed: 'निश्चित', journey_date_label: 'प्रवासाची तारीख', from_label: 'पासून', to_label: 'पर्यंत', download_ticket: 'E-Ticket डाउनलोड करा (PDF)',
        please_login_book: 'तिकीट बुक करण्यासाठी लॉगिन करा', registration_success: 'नोंदणी यशस्वी! कृपया लॉगिन करा.', logged_in: 'यशस्वीपणे लॉगिन झाले',
        login_modal_title: 'पुन्हा स्वागत आहे', login_modal_desc: 'बुकिंग आणि प्रोफाइलसाठी लॉगिन करा.', register_modal_title: 'AeroRail मध्ये सामील व्हा',
        register_modal_desc: 'बुकिंग सुरू करण्यासाठी खाते तयार करा.', username: 'वापरकर्ता नाव', password: 'पासवर्ड', dont_have_account: 'खाते नाही?',
        register_link: 'नोंदणी', already_have_account: 'आधीच खाते आहे?', login_link: 'लॉगिन', language: 'भाषा', create_account: 'खाते तयार करा', continue: 'पुढे चला'
    },
    ne: {
        home: 'होम', pnr_status: 'PNR स्थिति', live_tracking: 'लाइभ ट्र्याकिङ', login: 'लगइन / दर्ता', logout: 'लगआउट', my_account: 'मेरो खाता', hello: 'नमस्ते',
        book_ticket: 'टिकट बुक गर्नुहोस्', from_station: 'प्रस्थान स्टेशन', to_station: 'गन्तव्य स्टेशन', journey_date: 'यात्रा मिति', find_trains: 'ट्रेन खोज्नुहोस्',
        pnr_status_check: 'PNR स्थिति जाँच्नुहोस्', track_status: 'स्थिति जाँच्नुहोस्', search_trains: 'ट्रेन खोज्नुहोस्', passenger_details: 'यात्री विवरण',
        confirm_pay: 'पुष्टि गरी भुक्तानी गर्नुहोस्', total_amount: 'कुल रकम', no_trains_found: 'यो मार्ग र मितिका लागि कुनै ट्रेन भेटिएन।', live_status: 'लाइभ स्थिति',
        smartest_way: 'रेल यात्राको <br/>स्मार्ट तरिका।', book_track_pnr: 'टिकट बुक गर्नुहोस्, ट्रेन लाइभ ट्र्याक गर्नुहोस्, र PNR अपडेट पाउनुहोस्।',
        check_pnr_desc: 'लाइभ स्थितिका लागि आफ्नो 10 अंकको PNR नम्बर प्रविष्ट गर्नुहोस्।', book_now: 'अहिले बुक गर्नुहोस्', pnr_status_label: 'PNR स्थिति',
        charts_vacancy: 'चार्ट / खाली सीट', train_name_number: 'ट्रेन नाम / नम्बर', boarding_station: 'बोर्डिङ स्टेशन', get_train_chart: 'ट्रेन चार्ट पाउनुहोस्',
        enter_city_station: 'शहर/स्टेशन प्रविष्ट गर्नुहोस्', live_train_tracking: 'लाइभ ट्रेन ट्र्याकिङ', enter_train_number: 'लाइभ स्थान र स्थितिका लागि ट्रेन नम्बर प्रविष्ट गर्नुहोस्।',
        track_now: 'अहिले ट्र्याक गर्नुहोस्', my_bookings: 'मेरा बुकिङहरू', manage_journeys: 'आफ्ना यात्राहरू व्यवस्थापन गर्नुहोस्।', no_bookings: 'कुनै बुकिङ भेटिएन।',
        ticket_pdf: 'टिकट PDF', confirmed: 'पुष्टि भयो', journey_date_label: 'यात्रा मिति', from_label: 'बाट', to_label: 'सम्म', download_ticket: 'E-Ticket डाउनलोड गर्नुहोस् (PDF)',
        please_login_book: 'टिकट बुक गर्न लगइन गर्नुहोस्', registration_success: 'दर्ता सफल! कृपया लगइन गर्नुहोस्।', logged_in: 'सफलतापूर्वक लगइन भयो',
        login_modal_title: 'फेरि स्वागत छ', login_modal_desc: 'बुकिङ र प्रोफाइलका लागि लगइन गर्नुहोस्।', register_modal_title: 'AeroRail मा जोडिनुहोस्',
        register_modal_desc: 'बुकिङ सुरु गर्न खाता बनाउनुहोस्।', username: 'प्रयोगकर्ता नाम', password: 'पासवर्ड', dont_have_account: 'खाता छैन?',
        register_link: 'दर्ता', already_have_account: 'पहिले नै खाता छ?', login_link: 'लगइन', language: 'भाषा', create_account: 'खाता बनाउनुहोस्', continue: 'जारी राख्नुहोस्'
    },
    or: {
        home: 'ହୋମ୍', pnr_status: 'PNR ସ୍ଥିତି', live_tracking: 'ଲାଇଭ୍ ଟ୍ରାକିଂ', login: 'ଲଗିନ୍ / ରେଜିଷ୍ଟର', logout: 'ଲଗଆଉଟ୍', my_account: 'ମୋ ଖାତା', hello: 'ନମସ୍କାର',
        book_ticket: 'ଟିକେଟ୍ ବୁକ୍ କରନ୍ତୁ', from_station: 'ପ୍ରସ୍ଥାନ ଷ୍ଟେସନ୍', to_station: 'ଗନ୍ତବ୍ୟ ଷ୍ଟେସନ୍', journey_date: 'ଯାତ୍ରା ତାରିଖ', find_trains: 'ଟ୍ରେନ୍ ଖୋଜନ୍ତୁ',
        pnr_status_check: 'PNR ସ୍ଥିତି ଯାଞ୍ଚ କରନ୍ତୁ', track_status: 'ସ୍ଥିତି ଯାଞ୍ଚ କରନ୍ତୁ', search_trains: 'ଟ୍ରେନ୍ ଖୋଜନ୍ତୁ', passenger_details: 'ଯାତ୍ରୀ ବିବରଣୀ',
        confirm_pay: 'ନିଶ୍ଚିତ କରି ପେ କରନ୍ତୁ', total_amount: 'ମୋଟ ରାଶି', no_trains_found: 'ଏହି ରୁଟ୍ ଏବଂ ତାରିଖ ପାଇଁ କୌଣସି ଟ୍ରେନ୍ ମିଳିଲା ନାହିଁ।', live_status: 'ଲାଇଭ୍ ସ୍ଥିତି',
        smartest_way: 'ରେଳ ଯାତ୍ରାର <br/>ସ୍ମାର୍ଟ ଉପାୟ।', book_track_pnr: 'ଟିକେଟ୍ ବୁକ୍ କରନ୍ତୁ, ଟ୍ରେନ୍ ଲାଇଭ୍ ଟ୍ରାକ୍ କରନ୍ତୁ, ଏବଂ PNR ଅପଡେଟ୍ ପାଆନ୍ତୁ।',
        check_pnr_desc: 'ଲାଇଭ୍ ସ୍ଥିତି ପାଇଁ ଆପଣଙ୍କ 10 ଅଙ୍କର PNR ନମ୍ବର ଦିଅନ୍ତୁ।', book_now: 'ଏବେ ବୁକ୍ କରନ୍ତୁ', pnr_status_label: 'PNR ସ୍ଥିତି',
        charts_vacancy: 'ଚାର୍ଟ / ଖାଲି ଆସନ', train_name_number: 'ଟ୍ରେନ୍ ନାମ / ନମ୍ବର', boarding_station: 'ବୋର୍ଡିଂ ଷ୍ଟେସନ୍', get_train_chart: 'ଟ୍ରେନ୍ ଚାର୍ଟ ପାଆନ୍ତୁ',
        enter_city_station: 'ସହର/ଷ୍ଟେସନ୍ ଦିଅନ୍ତୁ', live_train_tracking: 'ଲାଇଭ୍ ଟ୍ରେନ୍ ଟ୍ରାକିଂ', enter_train_number: 'ଲାଇଭ୍ ସ୍ଥାନ ଏବଂ ସ୍ଥିତି ପାଇଁ ଟ୍ରେନ୍ ନମ୍ବର ଦିଅନ୍ତୁ।',
        track_now: 'ଏବେ ଟ୍ରାକ୍ କରନ୍ତୁ', my_bookings: 'ମୋ ବୁକିଂ', manage_journeys: 'ଆପଣଙ୍କ ଯାତ୍ରା ପରିଚାଳନା କରନ୍ତୁ।', no_bookings: 'କୌଣସି ବୁକିଂ ମିଳିଲା ନାହିଁ।',
        ticket_pdf: 'ଟିକେଟ୍ PDF', confirmed: 'ନିଶ୍ଚିତ', journey_date_label: 'ଯାତ୍ରା ତାରିଖ', from_label: 'ରୁ', to_label: 'ପର୍ଯ୍ୟନ୍ତ', download_ticket: 'E-Ticket ଡାଉନଲୋଡ୍ କରନ୍ତୁ (PDF)',
        please_login_book: 'ଟିକେଟ୍ ବୁକ୍ କରିବାକୁ ଲଗିନ୍ କରନ୍ତୁ', language: 'ଭାଷା', username: 'ବ୍ୟବହାରକାରୀ ନାମ', password: 'ପାସୱାର୍ଡ', login_link: 'ଲଗିନ୍', register_link: 'ରେଜିଷ୍ଟର'
    },
    pa: {
        home: 'ਹੋਮ', pnr_status: 'PNR ਸਥਿਤੀ', live_tracking: 'ਲਾਈਵ ਟ੍ਰੈਕਿੰਗ', login: 'ਲਾਗਇਨ / ਰਜਿਸਟਰ', logout: 'ਲਾਗਆਉਟ', my_account: 'ਮੇਰਾ ਖਾਤਾ', hello: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ',
        book_ticket: 'ਟਿਕਟ ਬੁੱਕ ਕਰੋ', from_station: 'ਰਵਾਨਗੀ ਸਟੇਸ਼ਨ', to_station: 'ਮੰਜ਼ਿਲ ਸਟੇਸ਼ਨ', journey_date: 'ਯਾਤਰਾ ਦੀ ਮਿਤੀ', find_trains: 'ਟ੍ਰੇਨ ਲੱਭੋ',
        pnr_status_check: 'PNR ਸਥਿਤੀ ਚੈਕ ਕਰੋ', track_status: 'ਸਥਿਤੀ ਚੈਕ ਕਰੋ', search_trains: 'ਟ੍ਰੇਨ ਲੱਭੋ', passenger_details: 'ਯਾਤਰੀ ਵੇਰਵੇ', confirm_pay: 'ਪੁਸ਼ਟੀ ਕਰੋ ਤੇ ਭੁਗਤਾਨ ਕਰੋ',
        total_amount: 'ਕੁੱਲ ਰਕਮ', no_trains_found: 'ਇਸ ਰੂਟ ਅਤੇ ਮਿਤੀ ਲਈ ਕੋਈ ਟ੍ਰੇਨ ਨਹੀਂ ਮਿਲੀ।', live_status: 'ਲਾਈਵ ਸਥਿਤੀ',
        smartest_way: 'ਰੇਲ ਯਾਤਰਾ ਦਾ <br/>ਸਮਾਰਟ ਤਰੀਕਾ।', book_track_pnr: 'ਟਿਕਟ ਬੁੱਕ ਕਰੋ, ਟ੍ਰੇਨ ਲਾਈਵ ਟ੍ਰੈਕ ਕਰੋ, ਅਤੇ PNR ਅਪਡੇਟ ਲਵੋ।',
        check_pnr_desc: 'ਲਾਈਵ ਸਥਿਤੀ ਲਈ ਆਪਣਾ 10 ਅੰਕਾਂ ਦਾ PNR ਨੰਬਰ ਦਰਜ ਕਰੋ।', book_now: 'ਹੁਣੇ ਬੁੱਕ ਕਰੋ', pnr_status_label: 'PNR ਸਥਿਤੀ',
        charts_vacancy: 'ਚਾਰਟ / ਖਾਲੀ ਸੀਟ', train_name_number: 'ਟ੍ਰੇਨ ਨਾਮ / ਨੰਬਰ', boarding_station: 'ਬੋਰਡਿੰਗ ਸਟੇਸ਼ਨ', get_train_chart: 'ਟ੍ਰੇਨ ਚਾਰਟ ਲਵੋ',
        enter_city_station: 'ਸ਼ਹਿਰ/ਸਟੇਸ਼ਨ ਦਰਜ ਕਰੋ', live_train_tracking: 'ਲਾਈਵ ਟ੍ਰੇਨ ਟ੍ਰੈਕਿੰਗ', enter_train_number: 'ਲਾਈਵ ਥਾਂ ਅਤੇ ਸਥਿਤੀ ਲਈ ਟ੍ਰੇਨ ਨੰਬਰ ਦਰਜ ਕਰੋ।',
        track_now: 'ਹੁਣੇ ਟ੍ਰੈਕ ਕਰੋ', my_bookings: 'ਮੇਰੀਆਂ ਬੁਕਿੰਗਾਂ', manage_journeys: 'ਆਪਣੀਆਂ ਯਾਤਰਾਵਾਂ ਸੰਭਾਲੋ।', no_bookings: 'ਕੋਈ ਬੁਕਿੰਗ ਨਹੀਂ ਮਿਲੀ।',
        ticket_pdf: 'ਟਿਕਟ PDF', confirmed: 'ਪੁਸ਼ਟੀ ਹੋਈ', journey_date_label: 'ਯਾਤਰਾ ਦੀ ਮਿਤੀ', from_label: 'ਤੋਂ', to_label: 'ਤੱਕ', download_ticket: 'E-Ticket ਡਾਊਨਲੋਡ ਕਰੋ (PDF)',
        please_login_book: 'ਟਿਕਟ ਬੁੱਕ ਕਰਨ ਲਈ ਲਾਗਇਨ ਕਰੋ', language: 'ਭਾਸ਼ਾ', username: 'ਯੂਜ਼ਰਨੇਮ', password: 'ਪਾਸਵਰਡ', login_link: 'ਲਾਗਇਨ', register_link: 'ਰਜਿਸਟਰ'
    },
    sa: {
        home: 'गृहम्', pnr_status: 'PNR स्थितिः', live_tracking: 'प्रत्यक्ष-अनुसरणम्', login: 'प्रवेशः / पञ्जीकरणम्', logout: 'निर्गमनम्', my_account: 'मम खाता', hello: 'नमस्ते',
        book_ticket: 'पत्रकं बुक् कुरुत', from_station: 'प्रस्थानस्थानकम्', to_station: 'गन्तव्यस्थानकम्', journey_date: 'यात्रा-दिनाङ्कः', find_trains: 'रेलयानानि अन्विष्यताम्',
        pnr_status_check: 'PNR स्थितिं पश्यत', track_status: 'स्थितिं पश्यत', search_trains: 'रेलयानानि अन्विष्यताम्', passenger_details: 'यात्रिक-विवरणम्', confirm_pay: 'निश्चयं कृत्वा मूल्यं ददातु',
        total_amount: 'समग्रं मूल्यं', no_trains_found: 'अस्मिन् मार्गे दिनाङ्के च रेलयानं न लब्धम्।', live_status: 'प्रत्यक्ष-स्थितिः',
        smartest_way: 'रेलयानेन यात्रायाः <br/>स्मार्ट उपायः।', book_track_pnr: 'पत्रकं बुक् कुरुत, रेलयानं अनुसरत, PNR अद्यतनं प्राप्नुत।',
        check_pnr_desc: 'प्रत्यक्षस्थित्यर्थं 10-अङ्कीयं PNR सङ्ख्यां लिखत।', book_now: 'अधुना बुक् कुरुत', pnr_status_label: 'PNR स्थितिः',
        charts_vacancy: 'चार्ट / रिक्तता', train_name_number: 'रेलयान-नाम / सङ्ख्या', boarding_station: 'आरोहण-स्थानकम्', get_train_chart: 'रेलयान-चार्ट प्राप्नुत',
        enter_city_station: 'नगरं/स्थानकं लिखत', live_train_tracking: 'प्रत्यक्ष रेलयान-अनुसरणम्', enter_train_number: 'स्थान-स्थित्यर्थं रेलयान-सङ्ख्यां लिखत।',
        track_now: 'अधुना अनुसरत', my_bookings: 'मम बुकिंग्', manage_journeys: 'स्वयात्राः व्यवस्थापयत।', no_bookings: 'बुकिंग् न लब्धम्।',
        ticket_pdf: 'पत्रक PDF', confirmed: 'निश्चितम्', journey_date_label: 'यात्रा-दिनाङ्कः', from_label: 'तः', to_label: 'पर्यन्तम्', download_ticket: 'E-Ticket अवतारयत (PDF)',
        please_login_book: 'पत्रकबुक् कर्तुं प्रवेशं कुरुत', language: 'भाषा', username: 'उपयोक्तृनाम', password: 'गुप्तशब्दः', login_link: 'प्रवेशः', register_link: 'पञ्जीकरणम्'
    },
    sat: {
        home: 'ᱚᱲᱟᱜ', pnr_status: 'PNR ᱫᱚᱥᱟ', live_tracking: 'ᱞᱟᱭᱵᱷ ᱴᱨᱮᱠᱤᱝ', login: 'ᱞᱚᱜᱤᱱ / ᱨᱮᱡᱤᱥᱴᱟᱨ', logout: 'ᱞᱚᱜᱟᱣᱩᱴ', my_account: 'ᱤᱧᱟᱜ ᱮᱠᱟᱣᱱᱴ', hello: 'ᱡᱚᱦᱟᱨ',
        book_ticket: 'ᱴᱤᱠᱮᱴ ᱵᱩᱠ ᱢᱮ', from_station: 'ᱮᱛᱦᱚᱵ ᱥᱴᱮᱥᱚᱱ', to_station: 'ᱥᱮᱛᱮᱨ ᱥᱴᱮᱥᱚᱱ', journey_date: 'ᱥᱮᱱ ᱢᱟᱦᱟᱸ', find_trains: 'ᱴᱨᱮᱱ ᱯᱟᱱᱛᱮ ᱢᱮ',
        pnr_status_check: 'PNR ᱫᱚᱥᱟ ᱧᱮᱞ ᱢᱮ', track_status: 'ᱫᱚᱥᱟ ᱧᱮᱞ ᱢᱮ', search_trains: 'ᱴᱨᱮᱱ ᱯᱟᱱᱛᱮ ᱢᱮ', passenger_details: 'ᱥᱮᱱᱤᱡ ᱵᱤᱵᱨᱚᱬ',
        confirm_pay: 'ᱴᱷᱤᱠ ᱟᱨ ᱯᱮ ᱢᱮ', total_amount: 'ᱢᱩᱴ ᱴᱟᱠᱟ', no_trains_found: 'ᱱᱚᱶᱟ ᱨᱩᱴ ᱟᱨ ᱢᱟᱦᱟᱸ ᱞᱟᱹᱜᱤᱫ ᱴᱨᱮᱱ ᱵᱟᱹᱱᱩᱜ।', live_status: 'ᱞᱟᱭᱵᱷ ᱫᱚᱥᱟ',
        smartest_way: 'ᱨᱮᱞ ᱥᱮᱱ ᱨᱮᱱᱟᱜ <br/>ᱥᱢᱟᱨᱴ ᱦᱚᱨ।', book_track_pnr: 'ᱴᱤᱠᱮᱴ ᱵᱩᱠ ᱢᱮ, ᱴᱨᱮᱱ ᱴᱨᱮᱠ ᱢᱮ, ᱟᱨ PNR ᱟᱯᱰᱮᱴ ᱧᱟᱢ ᱢᱮ।',
        check_pnr_desc: 'ᱞᱟᱭᱵᱷ ᱫᱚᱥᱟ ᱞᱟᱹᱜᱤᱫ 10 ᱟᱸᱠ PNR ᱱᱚᱢᱵᱚᱨ ᱮᱢ ᱢᱮ।', book_now: 'ᱱᱤᱛᱚᱜ ᱵᱩᱠ ᱢᱮ', pnr_status_label: 'PNR ᱫᱚᱥᱟ',
        charts_vacancy: 'ᱪᱟᱨᱴ / ᱠᱷᱟᱹᱞᱤ ᱥᱤᱴ', train_name_number: 'ᱴᱨᱮᱱ ᱧᱩᱛᱩᱢ / ᱱᱚᱢᱵᱚᱨ', boarding_station: 'ᱵᱚᱨᱰᱤᱝ ᱥᱴᱮᱥᱚᱱ', get_train_chart: 'ᱴᱨᱮᱱ ᱪᱟᱨᱴ ᱧᱟᱢ ᱢᱮ',
        enter_city_station: 'ᱥᱟᱦᱟᱨ/ᱥᱴᱮᱥᱚᱱ ᱮᱢ ᱢᱮ', live_train_tracking: 'ᱞᱟᱭᱵᱷ ᱴᱨᱮᱱ ᱴᱨᱮᱠᱤᱝ', track_now: 'ᱱᱤᱛᱚᱜ ᱴᱨᱮᱠ ᱢᱮ',
        my_bookings: 'ᱤᱧᱟᱜ ᱵᱩᱠᱤᱝ', no_bookings: 'ᱵᱩᱠᱤᱝ ᱵᱟᱹᱱᱩᱜ।', ticket_pdf: 'ᱴᱤᱠᱮᱴ PDF', confirmed: 'ᱴᱷᱤᱠ ᱟᱠᱟᱱᱟ', from_label: 'ᱠᱷᱚᱱ', to_label: 'ᱦᱟᱹᱵᱤᱡ', language: 'ᱯᱟᱹᱨᱥᱤ'
    },
    sd: {
        home: 'هوم', pnr_status: 'PNR حالت', live_tracking: 'لائيو ٽريڪنگ', login: 'لاگ ان / رجسٽر', logout: 'لاگ آئوٽ', my_account: 'منهنجو کاتو', hello: 'سلام',
        book_ticket: 'ٽڪيٽ بڪ ڪريو', from_station: 'روانگي اسٽيشن', to_station: 'منزل اسٽيشن', journey_date: 'سفر جي تاريخ', find_trains: 'ٽرينون ڳوليو',
        pnr_status_check: 'PNR حالت چيڪ ڪريو', track_status: 'حالت چيڪ ڪريو', search_trains: 'ٽرينون ڳوليو', passenger_details: 'مسافر تفصيل', confirm_pay: 'تصديق ۽ ادائيگي',
        total_amount: 'ڪل رقم', no_trains_found: 'هن روٽ ۽ تاريخ لاءِ ڪا ٽرين نه ملي.', live_status: 'لائيو حالت',
        smartest_way: 'ريل سفر جو <br/>سمارٽ طريقو.', book_track_pnr: 'ٽڪيٽ بڪ ڪريو، ٽرين لائيو ٽريڪ ڪريو، ۽ PNR اپڊيٽ وٺو.',
        check_pnr_desc: 'لائيو حالت لاءِ پنهنجو 10 انگن وارو PNR نمبر داخل ڪريو.', book_now: 'هاڻي بڪ ڪريو', pnr_status_label: 'PNR حالت',
        charts_vacancy: 'چارٽ / خالي سيٽ', train_name_number: 'ٽرين نالو / نمبر', boarding_station: 'بورڊنگ اسٽيشن', get_train_chart: 'ٽرين چارٽ وٺو',
        enter_city_station: 'شهر/اسٽيشن داخل ڪريو', live_train_tracking: 'لائيو ٽرين ٽريڪنگ', enter_train_number: 'لائيو هنڌ ۽ حالت لاءِ ٽرين نمبر داخل ڪريو.',
        track_now: 'هاڻي ٽريڪ ڪريو', my_bookings: 'منهنجون بڪنگون', manage_journeys: 'پنهنجا سفر منظم ڪريو.', no_bookings: 'ڪا بڪنگ نه ملي.',
        ticket_pdf: 'ٽڪيٽ PDF', confirmed: 'تصديق ٿيل', journey_date_label: 'سفر جي تاريخ', from_label: 'کان', to_label: 'تائين', download_ticket: 'E-Ticket ڊائونلوڊ ڪريو (PDF)',
        please_login_book: 'ٽڪيٽ بڪ ڪرڻ لاءِ لاگ ان ڪريو', language: 'ٻولي', username: 'يوزر نالو', password: 'پاسورڊ', login_link: 'لاگ ان', register_link: 'رجسٽر'
    },
    ta: {
        home: 'முகப்பு', pnr_status: 'PNR நிலை', live_tracking: 'நேரடி கண்காணிப்பு', login: 'உள்நுழை / பதிவு', logout: 'வெளியேறு', my_account: 'என் கணக்கு', hello: 'வணக்கம்',
        book_ticket: 'டிக்கெட் பதிவு செய்', from_station: 'புறப்படும் நிலையம்', to_station: 'செல்லும் நிலையம்', journey_date: 'பயண தேதி', find_trains: 'ரயில்களைத் தேடு',
        pnr_status_check: 'PNR நிலை பார்க்க', track_status: 'நிலை பார்க்க', search_trains: 'ரயில்களைத் தேடு', passenger_details: 'பயணி விவரங்கள்', confirm_pay: 'உறுதிசெய்து பணம் செலுத்து',
        total_amount: 'மொத்த தொகை', no_trains_found: 'இந்த வழி மற்றும் தேதிக்கான ரயில் கிடைக்கவில்லை.', live_status: 'நேரடி நிலை',
        smartest_way: 'ரயில் பயணத்தின் <br/>சிறந்த வழி.', book_track_pnr: 'டிக்கெட் பதிவு செய்யுங்கள், ரயில்களை நேரடியாக கண்காணியுங்கள், PNR புதுப்பிப்புகளைப் பெறுங்கள்.',
        check_pnr_desc: 'நேரடி நிலைக்கு உங்கள் 10 இலக்க PNR எண்ணை உள்ளிடுங்கள்.', book_now: 'இப்போது பதிவு செய்', pnr_status_label: 'PNR நிலை',
        charts_vacancy: 'சார்ட் / காலியிடம்', train_name_number: 'ரயில் பெயர் / எண்', boarding_station: 'ஏறும் நிலையம்', get_train_chart: 'ரயில் சார்ட் பெறு',
        enter_city_station: 'நகரம்/நிலையம் உள்ளிடு', live_train_tracking: 'நேரடி ரயில் கண்காணிப்பு', enter_train_number: 'நேரடி இடம் மற்றும் நிலைக்கு ரயில் எண்ணை உள்ளிடுங்கள்.',
        track_now: 'இப்போது கண்காணி', my_bookings: 'என் பதிவுகள்', manage_journeys: 'உங்கள் பயணங்களை நிர்வகிக்கவும்.', no_bookings: 'பதிவுகள் இல்லை.',
        ticket_pdf: 'டிக்கெட் PDF', confirmed: 'உறுதி செய்யப்பட்டது', journey_date_label: 'பயண தேதி', from_label: 'இருந்து', to_label: 'வரை', download_ticket: 'E-Ticket பதிவிறக்கு (PDF)',
        please_login_book: 'டிக்கெட் பதிவு செய்ய உள்நுழையுங்கள்', registration_success: 'பதிவு வெற்றி! தயவுசெய்து உள்நுழையுங்கள்.', logged_in: 'வெற்றிகரமாக உள்நுழைந்தீர்கள்',
        login_modal_title: 'மீண்டும் வரவேற்கிறோம்', login_modal_desc: 'பதிவுகள் மற்றும் சுயவிவரத்துக்கு உள்நுழையுங்கள்.', register_modal_title: 'AeroRail-இல் சேருங்கள்',
        register_modal_desc: 'பதிவு தொடங்க கணக்கு உருவாக்குங்கள்.', username: 'பயனர்பெயர்', password: 'கடவுச்சொல்', dont_have_account: 'கணக்கு இல்லையா?',
        register_link: 'பதிவு', already_have_account: 'ஏற்கனவே கணக்கு உள்ளதா?', login_link: 'உள்நுழை', language: 'மொழி', create_account: 'கணக்கு உருவாக்கு', continue: 'தொடரவும்'
    },
    te: {
        home: 'హోమ్', pnr_status: 'PNR స్థితి', live_tracking: 'లైవ్ ట్రాకింగ్', login: 'లాగిన్ / రిజిస్టర్', logout: 'లాగౌట్', my_account: 'నా ఖాతా', hello: 'నమస్కారం',
        book_ticket: 'టికెట్ బుక్ చేయండి', from_station: 'ప్రారంభ స్టేషన్', to_station: 'గమ్య స్టేషన్', journey_date: 'ప్రయాణ తేదీ', find_trains: 'రైళ్లను వెతకండి',
        pnr_status_check: 'PNR స్థితి చూడండి', track_status: 'స్థితి చూడండి', search_trains: 'రైళ్లను వెతకండి', passenger_details: 'ప్రయాణికుల వివరాలు',
        confirm_pay: 'నిర్ధారించి చెల్లించండి', total_amount: 'మొత్తం', no_trains_found: 'ఈ మార్గం మరియు తేదీకి రైలు దొరకలేదు.', live_status: 'లైవ్ స్థితి',
        smartest_way: 'రైలు ప్రయాణానికి <br/>స్మార్ట్ మార్గం.', book_track_pnr: 'టికెట్లు బుక్ చేయండి, రైళ్లను లైవ్ ట్రాక్ చేయండి, PNR అప్డేట్లు పొందండి.',
        check_pnr_desc: 'లైవ్ స్థితి కోసం మీ 10 అంకెల PNR నంబర్ నమోదు చేయండి.', book_now: 'ఇప్పుడే బుక్ చేయండి', pnr_status_label: 'PNR స్థితి',
        charts_vacancy: 'చార్ట్ / ఖాళీలు', train_name_number: 'రైలు పేరు / నంబర్', boarding_station: 'బోర్డింగ్ స్టేషన్', get_train_chart: 'రైలు చార్ట్ పొందండి',
        enter_city_station: 'నగరం/స్టేషన్ నమోదు చేయండి', live_train_tracking: 'లైవ్ రైలు ట్రాకింగ్', enter_train_number: 'లైవ్ స్థానం మరియు స్థితి కోసం రైలు నంబర్ నమోదు చేయండి.',
        track_now: 'ఇప్పుడే ట్రాక్ చేయండి', my_bookings: 'నా బుకింగ్స్', manage_journeys: 'మీ ప్రయాణాలను నిర్వహించండి.', no_bookings: 'బుకింగ్స్ లేవు.',
        ticket_pdf: 'టికెట్ PDF', confirmed: 'నిర్ధారించబడింది', journey_date_label: 'ప్రయాణ తేదీ', from_label: 'నుండి', to_label: 'వరకు', download_ticket: 'E-Ticket డౌన్‌లోడ్ చేయండి (PDF)',
        please_login_book: 'టికెట్ బుక్ చేయడానికి లాగిన్ చేయండి', registration_success: 'రిజిస్ట్రేషన్ విజయవంతం! దయచేసి లాగిన్ చేయండి.', logged_in: 'విజయవంతంగా లాగిన్ అయ్యారు',
        login_modal_title: 'మళ్లీ స్వాగతం', login_modal_desc: 'బుకింగ్స్ మరియు ప్రొఫైల్ కోసం లాగిన్ చేయండి.', register_modal_title: 'AeroRail లో చేరండి',
        register_modal_desc: 'బుకింగ్ ప్రారంభించడానికి ఖాతా సృష్టించండి.', username: 'వినియోగదారు పేరు', password: 'పాస్‌వర్డ్', dont_have_account: 'ఖాతా లేదా?',
        register_link: 'రిజిస్టర్', already_have_account: 'ఇప్పటికే ఖాతా ఉందా?', login_link: 'లాగిన్', language: 'భాష', create_account: 'ఖాతా సృష్టించండి', continue: 'కొనసాగించండి'
    },
    ur: {
        home: 'ہوم', pnr_status: 'PNR اسٹیٹس', live_tracking: 'لائیو ٹریکنگ', login: 'لاگ اِن / رجسٹر', logout: 'لاگ آؤٹ', my_account: 'میرا اکاؤنٹ', hello: 'السلام علیکم',
        book_ticket: 'ٹکٹ بک کریں', from_station: 'روانگی اسٹیشن', to_station: 'منزل اسٹیشن', journey_date: 'سفر کی تاریخ', find_trains: 'ٹرینیں تلاش کریں',
        pnr_status_check: 'PNR اسٹیٹس چیک کریں', track_status: 'اسٹیٹس چیک کریں', search_trains: 'ٹرینیں تلاش کریں', passenger_details: 'مسافر کی تفصیلات', confirm_pay: 'تصدیق کریں اور ادائیگی کریں',
        total_amount: 'کل رقم', no_trains_found: 'اس روٹ اور تاریخ کے لیے کوئی ٹرین نہیں ملی۔', live_status: 'لائیو اسٹیٹس',
        smartest_way: 'ریل سے سفر کا <br/>سمارٹ طریقہ۔', book_track_pnr: 'ٹکٹ بک کریں، ٹرینیں لائیو ٹریک کریں، اور PNR اپڈیٹس حاصل کریں۔',
        check_pnr_desc: 'لائیو اسٹیٹس کے لیے اپنا 10 ہندسوں کا PNR نمبر درج کریں۔', book_now: 'ابھی بک کریں', pnr_status_label: 'PNR اسٹیٹس',
        charts_vacancy: 'چارٹ / خالی نشست', train_name_number: 'ٹرین نام / نمبر', boarding_station: 'بورڈنگ اسٹیشن', get_train_chart: 'ٹرین چارٹ حاصل کریں',
        enter_city_station: 'شہر/اسٹیشن درج کریں', live_train_tracking: 'لائیو ٹرین ٹریکنگ', enter_train_number: 'لائیو مقام اور اسٹیٹس کے لیے ٹرین نمبر درج کریں۔',
        track_now: 'ابھی ٹریک کریں', my_bookings: 'میری بکنگز', manage_journeys: 'اپنے سفر منظم کریں۔', no_bookings: 'کوئی بکنگ نہیں ملی۔',
        ticket_pdf: 'ٹکٹ PDF', confirmed: 'تصدیق شدہ', journey_date_label: 'سفر کی تاریخ', from_label: 'سے', to_label: 'تک', download_ticket: 'E-Ticket ڈاؤنلوڈ کریں (PDF)',
        please_login_book: 'ٹکٹ بک کرنے کے لیے لاگ اِن کریں', registration_success: 'رجسٹریشن کامیاب! براہ کرم لاگ اِن کریں۔', logged_in: 'کامیابی سے لاگ اِن ہو گئے',
        login_modal_title: 'خوش آمدید', login_modal_desc: 'بکنگز اور پروفائل تک رسائی کے لیے لاگ اِن کریں۔', register_modal_title: 'AeroRail میں شامل ہوں',
        register_modal_desc: 'بکنگ شروع کرنے کے لیے اکاؤنٹ بنائیں۔', username: 'صارف نام', password: 'پاس ورڈ', dont_have_account: 'اکاؤنٹ نہیں ہے؟',
        register_link: 'رجسٹر', already_have_account: 'پہلے سے اکاؤنٹ ہے؟', login_link: 'لاگ اِن', language: 'زبان', create_account: 'اکاؤنٹ بنائیں', continue: 'جاری رکھیں'
    }
};

export const i18n = SUPPORTED_LANGUAGES.reduce((packs, language) => {
    packs[language.code] = { ...en, ...(languageOverrides[language.code] || {}) };
    return packs;
}, {});

const savedLanguage = localStorage.getItem('aeroRailLanguage') || 'en';
const supportedCodes = new Set(SUPPORTED_LANGUAGES.map(language => language.code));

export const state = {
    user: null,
    role: 'customer',
    currentPath: window.location.pathname,
    searchResults: [],
    selectedTrain: null,
    isRegistering: false,
    language: supportedCodes.has(savedLanguage) ? savedLanguage : 'en',
    searchDate: new Date().toISOString().split('T')[0]
};

export function t(key) {
    return i18n[state.language] && i18n[state.language][key]
        ? i18n[state.language][key]
        : i18n.en[key] || key;
}
